struct Note {
  int pitch;    // Frequency of the note
  float duration; // Duration of the note (in terms of note type)
};

Note melody[] = {
  {NOTE_G5, HALF_NOTE}, 
  {NOTE_E5, QUARTER_NOTE + EIGHTH_NOTE}, 
  {NOTE_F5, EIGHTH_NOTE},

  {NOTE_A5, EIGHTH_NOTE},
  {NOTE_G5, EIGHTH_NOTE},
  {NOTE_F5, EIGHTH_NOTE},
  {NOTE_E5, EIGHTH_NOTE},
  {NOTE_E5, QUARTER_NOTE},
  {SILENCE, QUARTER_NOTE},

  {NOTE_F5, QUARTER_NOTE},
  {NOTE_D5, EIGHTH_NOTE},
  {SILENCE, EIGHTH_NOTE},
  {NOTE_F5, QUARTER_NOTE},
  {NOTE_D5, EIGHTH_NOTE},
  {SILENCE, EIGHTH_NOTE},

  {NOTE_C5, HALF_NOTE},
  {NOTE_B4, QUARTER_NOTE},
  {SILENCE, QUARTER_NOTE},

  {NOTE_C5, HALF_NOTE + SIXTEENTH_NOTE},
  {NOTE_B4, SIXTEENTH_NOTE},
  {NOTE_C5, SIXTEENTH_NOTE},
  {NOTE_B4, SIXTEENTH_NOTE},
  {NOTE_D5, SIXTEENTH_NOTE},
  {NOTE_C5, SIXTEENTH_NOTE},
  {NOTE_B4, SIXTEENTH_NOTE},
  {NOTE_A4, SIXTEENTH_NOTE},

  {NOTE_G4, EIGHTH_NOTE},
  {NOTE_F5, EIGHTH_NOTE},
  {NOTE_F5, HALF_NOTE},
  {NOTE_E5, QUARTER_NOTE},

  {NOTE_D5, SIXTEENTH_NOTE},
  {NOTE_E5, SIXTEENTH_NOTE},
  {NOTE_F5, SIXTEENTH_NOTE},
  {NOTE_G5, SIXTEENTH_NOTE},
  {NOTE_GS5, SIXTEENTH_NOTE},
  {NOTE_A5, SIXTEENTH_NOTE},
  {NOTE_F5, SIXTEENTH_NOTE},
  {NOTE_D5, SIXTEENTH_NOTE},
  {NOTE_C5, QUARTER_NOTE},
  {NOTE_E5, EIGHTH_NOTE},
  {NOTE_D5, EIGHTH_NOTE},
  
  {NOTE_C5, QUARTER_NOTE},
  {SILENCE, HALF_NOTE + QUARTER_NOTE},
};